[package]
name = "qem"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rayon = "1.10.0"
numpy = "0.21.0"
num-traits = "0.2.18"
num-complex = { version = "0.4.5" }
pyo3 = { version = "0.27.2", features = ["extension-module", "num-complex"] }
